var isNode = 'undefined' !== typeof global && '[object global]' === {}.toString.call(global);
var Abacus = isNode ? require('../src/js/Abacus.js') : window.Abacus, echo = console.log;
var use_biginteger_arithmetic = require('./biginteger/arithmetic.js');

use_biginteger_arithmetic( Abacus );

var pring, ring;

ring = Abacus.Ring.C("x");
echo('ring = Abacus.Ring.'+ring.toString());
echo('----');
echo('ring.fromString("1")');
echo(ring.fromString("1").toString());
echo('ring.fromString("1 + x^2")');
echo(ring.fromString("1 + x^2").toString());
echo('ring.fromString("1 - x^2")');
echo(ring.fromString("1 - x^2").toString());
echo('ring.fromString("1 - (2/3)*x^2+x")');
echo(ring.fromString("1 - (2/3)*x^2+x").toString());
echo('ring.fromString("1 - \\frac{2}{3}*x^{2}+x")');
echo(ring.fromString("1 - \\frac{2}{3}*x^{2}+x").toString());
echo('ring.fromString("1 - x")');
echo(ring.fromString("1 - x").toString())
echo('ring.fromString("1 + y")');
echo(ring.fromString("1 + y").toString());
echo('ring.fromString(ring.create([Abacus.Complex.Img(), Abacus.Complex(2,-1)]).toString())');
echo(ring.fromString(ring.create([Abacus.Complex.Img(), Abacus.Complex(2,-1)]).toString()).toString());
echo('ring.fromString("ix^2+1")');
echo(ring.fromString("ix^2+1").toString());
echo('ring.fromString("(1/2+i)x^2+3/2")');
echo(ring.fromString("(1/2+i)x^2+3/2").toString());
echo('ring.fromString("(1/2)ix^2+(1+(2/3)i)x")');
echo(ring.fromString("(1/2)ix^2+(1+(2/3)i)x").toString());
echo('ring.fromString("(3/2+(1/2)i)x+1+(2/3)i")');
echo(ring.fromString("(3/2+(1/2)i)x+1+(2/3)i").toString());
echo('ring.fromString("1+2ix") /* this is taken as one complex coefficient unfortunately */');
echo(ring.fromString("1+2ix").toString());
echo('ring.fromString("1+(2i)x") /* this is taken as one complex coefficient unfortunately */');
echo(ring.fromString("1+(2i)x").toString());
echo('ring.fromString("1+((2)i)x") /* this is workaround, parsed correctly */');
echo(ring.fromString("1+((2)i)x").toString());
echo('ring.fromString("2ix+1") /* this is workaround, parsed correctly, in fact .toString() methods output strings in this order so always parsed correctly */');
echo(ring.fromString("2ix+1").toString());
echo();

ring = Abacus.Ring.C("x","y","z");
echo('ring = Abacus.Ring.'+ring.toString());
echo('----');
echo('ring.fromString("1 - yx^2 + 3xy")');
echo(ring.fromString("1 - yx^2 + 3xy").toString());
echo('ring.fromString("1 - yx")');
echo(ring.fromString("1 - yx").toString());
echo('ring.fromString("1 - y+x")');
echo(ring.fromString("1 - y+x").toString());
echo('ring.fromString("1+xy+xy^2")');
echo(ring.fromString("1+xy+xy^2").toString());
echo('ring.fromString("1 - yx")');
echo(ring.fromString("1 - yx").toString());
echo('ring.fromString("1+xy+xy^2")');
echo(ring.fromString("1+xy+xy^2").toString());
echo('ring.fromString("x^2y+x^2y^2+x+yx+2")');
echo(ring.fromString("x^2y+x^2y^2+x+yx+2").toString());
echo('ring.fromString("x^2y+x^2y^2+x+yx+2+zyx+zy")');
echo(ring.fromString("x^2y+x^2y^2+x+yx+2+zyx+zy").toString());
echo();

pring = Abacus.Ring.C("x", "y"); ring = pring.fieldOfFractions();
echo('ring = Abacus.Ring.'+ring.toString());
echo('----');
echo('ring.fromString("(1+xy)/(x-y)")');
echo(ring.fromString("(1+xy)/(x-y)").toString());
echo('ring.fromString("(1+i)/(x-y)")');
echo(ring.fromString("(1+i)/(x-y)").toString());
echo('ring.fromString("(3x+(1+i))/(1+i)")');
echo(ring.fromString("(3x+(1+i))/(1+i)").toString());
echo('ring.fromString("1/(x-y)")');
echo(ring.fromString("1/(x-y)").toString());
echo('ring.fromString("1/(3/2)x")');
echo(ring.fromString("1/(3/2)x").toString());
echo('ring.fromString("(3/2)/x")');
echo(ring.fromString("(3/2)/x").toString());
echo('ring.fromString("x-y")');
echo(ring.fromString("x-y").toString());
echo('ring.fromString("3/2")');
echo(ring.fromString("3/2").toString());
echo('ring.fromString("xy+3/2")');
echo(ring.fromString("xy+3/2").toString());
