@echo off
rem @echo off

call node numbers.js > numbers.txt
call node rationals.js > rationals.txt
call node complex.js > complex.txt
call node number_theory.js > number_theory.txt
call node progressions.js > progressions.txt
call node polynomials.js > polynomials.txt
call node multivariate.js > multivariate.txt
call node ratfuncs.js > ratfuncs.txt
call node matrices.js > matrices.txt
call node expressions.js > expressions.txt
call node primes.js > primes.txt
call node diophantine.js > diophantine.txt
call node tensors.js > tensors.txt
call node tuples.js > tuples.txt
call node permutations.js > permutations.txt
call node multiset_permutations.js > multiset_permutations.txt
call node derangements.js > derangements.txt
call node involutions.js > involutions.txt
call node connected_permutations.js > connected_permutations.txt
call node permutations-bigint.js > permutations-bigint.txt
call node cyclic_permutations.js > cyclic_permutations.txt
call node recursive_permutations.js > recursive_permutations.txt
call node combinations.js > combinations.txt
call node ordered_combinations.js > ordered_combinations.txt
call node combinations_repeats.js > combinations_repeats.txt
call node ordered_combinations_repeats.js > ordered_combinations_repeats.txt
call node permutations_of_combinations.js > permutations_of_combinations.txt
call node permutations_of_permutations.js > permutations_of_permutations.txt
call node subsets.js > subsets.txt
call node combination_subsets.js > combination_subsets.txt
call node partitions.js > partitions.txt
call node compositions.js > compositions.txt
call node restricted_partitions.js > restricted_partitions.txt
call node restricted_compositions.js > restricted_compositions.txt
call node filtered_partitions.js > filtered_partitions.txt
call node filtered_compositions.js > filtered_compositions.txt
call node k-derangements.js > k-derangements.txt
call node partially_fixed_permutations.js > partially_fixed_permutations.txt
call node conditional_permutations_boolean.js > conditional_permutations_boolean.txt
call node conditional_permutations_algebraic.js > conditional_permutations_algebraic.txt
call node filtered.js > filtered.txt
call node latin_squares.js > latin_squares.txt
call node magic_squares.js > magic_squares.txt
